/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("jvm") version "1.9.10" 
    id("nu.studer.jooq") version "9.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // JOOQ runtime
    implementation("org.jooq:jooq:3.19.1")

    implementation("mysql:mysql-connector-java:8.0.33")

    // Driver MySQL per jOOQ Generator
    jooqGenerator("mysql:mysql-connector-java:8.0.33")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// jOOQ configuration per MySQL
jooq {
    version.set("3.19.1")
    configurations {
        create("main") {
            generationTool {
                jdbc {
                    driver = "com.mysql.cj.jdbc.Driver"
                    url = "jdbc:mysql://localhost:3306/Adozione_Animali"
                }
                generator {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database {
                        name = "org.jooq.meta.mysql.MySQLDatabase"
                        inputSchema = "Adozione_Animali"
                    }
                    target {
                        packageName = "jooq.generated"
                        directory = "build/generated-src/jooq/main"
                    }
                }
            }
        }
    }
}


application {
    // Define the main class for the application.
    mainClass = "it.unibo.adozione_animali.Start"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

sourceSets["main"].java.srcDir("build/generated-src/jooq/main")
